### PR TITLE
Pan4532

### PR DESCRIPTION
**Pull request by natashapinto**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/232)

### CODE REVIEW

**Review by aledj2 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 2 of 8 files at r2, 1 of 2 files at r9, 1 of 2 files at r10, 1 of 2 files at r13, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/232)* status: 7 of 13 files reviewed, all discussions resolved (waiting on @natashapinto)

**Review by aledj2 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/232#-:-Mdr6dwQCo75YkmlirAe:bg7igkv)* status: 7 of 13 files reviewed, all discussions resolved (waiting on @natashapinto)

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/232)* status: 7 of 13 files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[LiveBedfiles/RequestForms/Pan4532.csv, line 16 at r13](https://reviewable.io/reviews/moka-guys/mokabed/232#-MdujsEmCuluVtXVAvcb:-MdujsEn8ffCnVMQUOOw:bkq5xpy) ([raw file](https://github.com/moka-guys/mokabed/blob/04ddf40c4f0752c9563402ff0012cada325fee55/LiveBedfiles/RequestForms/Pan4532.csv#L16)):*
> ```CSV
> 4. b) If yes, does this need further padding?",N/A,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> 5. a) Should specific transcripts be used to create the bed file? (as opposed to all transcripts) Specific transcripts - see Moka,Yes - see below,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> 5. b) If specific transcripts are to be used have you provided multiple transcripts for the same gene? (if Yes please state),No,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> ```

i think the answer is yes here

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/232)* status: 6 of 13 files reviewed, 2 unresolved discussions (waiting on @natashapinto)

___
*[LiveBedfiles/Pan4532dataRefSeqFormat.txt, line 1 at r2](https://reviewable.io/reviews/moka-guys/mokabed/232#-Mdvnjf3ClyvD5v0Ix7Y:-Mdvnjf3ClyvD5v0Ix7Z:bnkbqxo) ([raw file](https://github.com/moka-guys/mokabed/blob/a7060ac660b2bd3d46fb18a969f67ffb0bb04546/LiveBedfiles/Pan4532dataRefSeqFormat.txt#L1)):*
> ```help
> #bin	name	chrom	strand	txStart	txEnd	cdsStart	cdsEnd	exonCount	exonStarts	exonSEnds	score	name2	cdsStartStat	cdsEndStat	exonFrames
> ```

incomplete so shouldn't be kept

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/232)* status: 4 of 13 files reviewed, 1 unresolved discussion (waiting on @aledj2 and @natashapinto)

___
*[LiveBedfiles/RequestForms/Pan4532.csv, line 18 at r16](https://reviewable.io/reviews/moka-guys/mokabed/232#-MdwN4GFBscSXhI7epg9:-MdwN4GFBscSXhI7epgA:b-kk03fb) ([raw file](https://github.com/moka-guys/mokabed/blob/93501d0d94e81c2e895d353596e04df056d4ee80/LiveBedfiles/RequestForms/Pan4532.csv#L18)):*
> ```CSV
> 5. b) If specific transcripts are to be used have you provided multiple transcripts for the same gene? (if Yes please state),Yes,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> 6. What padding is required around the exons?,30bp,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> 7. a) Should UTRs be included for ALL genes?,N/A,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> ```

sorry!

**Review by natashapinto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/232)* status: 4 of 13 files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[LiveBedfiles/RequestForms/Pan4532.csv, line 18 at r16](https://reviewable.io/reviews/moka-guys/mokabed/232#-MdwN4GFBscSXhI7epg9:-MdwWmub6DH54Y12D1Hd:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/93501d0d94e81c2e895d353596e04df056d4ee80/LiveBedfiles/RequestForms/Pan4532.csv#L18)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

sorry!
</blockquote></details>

Done.

**Review by aledj2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/232#-:-MdwX-02EBiJH_f-3Tb8:bnfp4nl)* status: 6 of 13 files reviewed, all discussions resolved (waiting on @natashapinto)

**Pull request merged**
