### PR TITLE
add intronic variants

### PR DESCRIPTION
**Pull request by natashapinto**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/178)

### CODE REVIEW

**Review by aledj2 — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/178)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @natashapinto)

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/178)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[LiveBedfiles/Pan4272.bed, line 3 at r1](https://reviewable.io/reviews/moka-guys/mokabed/178#-MS2kanE9Y1XR8r5hy7A:-MS2kanFC-0dGwNRE6QG:b-3qix3m) ([raw file](https://github.com/moka-guys/mokabed/blob/79822d09454a36a61ef0fc9de242a1789492dda2/LiveBedfiles/Pan4272.bed#L3)):*
> ```
> 7   117229515   117229526   rs397508266
> 7   117280009   117280020   rs75039782		
> 7   117179036   117179049   rs397508809
> ```

can you check for empty newline please

**Comment by natashapinto** [comment]
Sorry accidentally pushed an incomplete logfile

**Review by aledj2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/178)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[LiveBedfiles/Pan4272.bed, line 2 at r2](https://reviewable.io/reviews/moka-guys/mokabed/178#-MS3IkN04TSM5H1XrHAc:-MS3IkN04TSM5H1XrHAd:bu07t19) ([raw file](https://github.com/moka-guys/mokabed/blob/b3430ee7afb250d111cdb0d348d473a365b48722/LiveBedfiles/Pan4272.bed#L2)):*
> ```
> 7   117229515   117229526   rs397508266
> 7   117280009   117280020   rs75039782		
> ```

Nearly there... is there an extra tab at the end of this line?

**Comment by natashapinto** [comment]
fixed the extra tabs

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/178)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[LiveBedfiles/Pan4272.bed, line 2 at r2](https://reviewable.io/reviews/moka-guys/mokabed/178#-MS3IkN04TSM5H1XrHAc:-MS3Mcyz-CcrXaprnCps:b-uilmzx) ([raw file](https://github.com/moka-guys/mokabed/blob/b3430ee7afb250d111cdb0d348d473a365b48722/LiveBedfiles/Pan4272.bed#L2)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Nearly there... is there an extra tab at the end of this line?
</blockquote></details>

sorry, is there still one there?

**Review by aledj2 — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/178)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @natashapinto)

**Pull request merged**
