### PR TITLE
Pan4571

### PR DESCRIPTION
**Pull request by natashapinto**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/239)

### CODE REVIEW

**Review by aledj2 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r2, 3 of 16 files at r3, 1 of 2 files at r12, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/239)* status: 9 of 23 files reviewed, 2 unresolved discussions (waiting on @natashapinto)

___
*[LiveBedfiles/Pan4571dataRefSeqFormat.txt, line 1 at r14](https://reviewable.io/reviews/moka-guys/mokabed/239#-MdvnQXf6Pvm8pYNUqD1:-MdvnQXgDvLhur7sitJS:bjlzisv) ([raw file](https://github.com/moka-guys/mokabed/blob/79608e5e0c29f8d4e330ef5388a80730a593b145/LiveBedfiles/Pan4571dataRefSeqFormat.txt#L1)):*
> ```help
> #bin	name	chrom	strand	txStart	txEnd	cdsStart	cdsEnd	exonCount	exonStarts	exonSEnds	score	name2	cdsStartStat	cdsEndStat	exonFrames
> ```

should we delete this as it's incomplete?
___
*[LiveBedfiles/RequestForms/Pan4571.csv, line 16 at r2](https://reviewable.io/reviews/moka-guys/mokabed/239#-MdvlkiC4VBLU4pIxw0r:-MdvlkiDDOj7pkRsfGUs:b2nign6) ([raw file](https://github.com/moka-guys/mokabed/blob/28ce51f0eb82c38a261afcdb23a740de9707f1ec/LiveBedfiles/RequestForms/Pan4571.csv#L16)):*
> ```CSV
> 4. b) If yes, does this need further padding?",N/A,
> 5. a) Should specific transcripts be used to create the bed file? (as opposed to all transcripts) Specific transcripts - see Moka,Yes - see below,
> 5. b) If specific transcripts are to be used have you provided multiple transcripts for the same gene? (if Yes please state),No,
> ```

yes

**Review by natashapinto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/239)* status: 8 of 23 files reviewed, 2 unresolved discussions (waiting on @aledj2)

___
*[LiveBedfiles/RequestForms/Pan4571.csv, line 16 at r2](https://reviewable.io/reviews/moka-guys/mokabed/239#-MdvlkiC4VBLU4pIxw0r:-Mdw6BtP0oAUOf0e9lgX:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/28ce51f0eb82c38a261afcdb23a740de9707f1ec/LiveBedfiles/RequestForms/Pan4571.csv#L16)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Done.
___
*[LiveBedfiles/Pan4571dataRefSeqFormat.txt, line 1 at r14](https://reviewable.io/reviews/moka-guys/mokabed/239#-MdvnQXf6Pvm8pYNUqD1:-Mdw6G9S3FdJ_SJbg4p6:bhofej8) ([raw file](https://github.com/moka-guys/mokabed/blob/79608e5e0c29f8d4e330ef5388a80730a593b145/LiveBedfiles/Pan4571dataRefSeqFormat.txt#L1)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

should we delete this as it's incomplete?
</blockquote></details>

Deleted

**Review by aledj2 — APPROVED** [review]
> Reviewed 1 of 2 files at r16, 1 of 1 files at r18.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/239)* status: 10 of 23 files reviewed, all discussions resolved (waiting on @natashapinto)

**Review by aledj2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/239)* status: 10 of 23 files reviewed, all discussions resolved (waiting on @natashapinto)

**Pull request merged**
