### PR TITLE
Pan3638

### PR DESCRIPTION
**Pull request by aledj2**
New BED file for SWFT EGFR that ensures super amplicons are included in the coverage (Pan3638Sambamba.bed), QC (Pan3638.bed) and variant calling (Pan3638_flat.bed). Based on Pan1190 bed files

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/160)

### CODE REVIEW

**Comment by Graeme-Smith** [comment]
___
*[LiveBedfiles/Pan3638.log, line 45 at r5](https://reviewable.io/reviews/moka-guys/mokabed/160#-MNTXTqX56SvLcUeKFoG:-MNTXTqYB_vPGfNEX6ds:b2qp2yt) ([raw file](https://github.com/moka-guys/mokabed/blob/24dff8b9a65ff023c95ecf2be94049299f1f437e/LiveBedfiles/Pan3638.log#L45)):*
> ```
> 003_201130_Pan3638_test
> ```
I couldn't see this project in DNA nexus, is teh project name correct?

**Comment by Graeme-Smith** [comment]
___
*[LiveBedfiles/Pan3638.log, line 17 at r2](https://reviewable.io/reviews/moka-guys/mokabed/160#-MNTY0nS2RWJDUq4Xyde:-MNTY0nTEapta8BwaaCm:bivs1vi) ([raw file](https://github.com/moka-guys/mokabed/blob/dbfcb256140c2b106afa00a8d048935f45067bca/LiveBedfiles/Pan3638.log#L17)):*
> ```
> 
> #Pan3638data.bed
> This BED file is used to generate QC and was used to create the bed files described below.
> ```

I cannot see any version control for Pan3638data.bed, do you mean Pan3638.bed?

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/160)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @aledj2 and @Graeme-Smith)

___
*[LiveBedfiles/Pan3638.log, line 45 at r5](https://reviewable.io/reviews/moka-guys/mokabed/160#-MNTXTqX56SvLcUeKFoG:-MNTYMb37ZwRDyfKEo-h:bd0o1km) ([raw file](https://github.com/moka-guys/mokabed/blob/24dff8b9a65ff023c95ecf2be94049299f1f437e/LiveBedfiles/Pan3638.log#L45)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

> ```
> 003_201130_Pan3638_test
> ```
I couldn't see this project in DNA nexus, is teh project name correct?
</blockquote></details>

my bad, wasn't shared. try now

**Review by Graeme-Smith — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/160)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2)

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/160)* status: all files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith)

___
*[LiveBedfiles/Pan3638.log, line 17 at r2](https://reviewable.io/reviews/moka-guys/mokabed/160#-MNTY0nS2RWJDUq4Xyde:-MNTYQmm8GFheKN99ESs:byvdizx) ([raw file](https://github.com/moka-guys/mokabed/blob/dbfcb256140c2b106afa00a8d048935f45067bca/LiveBedfiles/Pan3638.log#L17)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

I cannot see any version control for Pan3638data.bed, do you mean Pan3638.bed?
</blockquote></details>

yes - will change

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/160)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith)

___
*[LiveBedfiles/Pan3638.log, line 17 at r2](https://reviewable.io/reviews/moka-guys/mokabed/160#-MNTY0nS2RWJDUq4Xyde:-MNTZ4TN9pWAfefiF8FN:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/dbfcb256140c2b106afa00a8d048935f45067bca/LiveBedfiles/Pan3638.log#L17)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

yes - will change
</blockquote></details>

Done.

**Review by Graeme-Smith — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/160)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
