### PR TITLE
add flat file for varscan

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/159)

### CODE REVIEW

**Comment by Graeme-Smith** [comment]
___
*[LiveBedfiles/Pan4011_log.md, line 37 at r1](https://reviewable.io/reviews/moka-guys/mokabed/159#-MLsBtTc0yjIVbMlZbDq:-MLsBtTd2UBCq2_JFRfp:b-5qvcxq) ([raw file](https://github.com/moka-guys/mokabed/blob/8b33ce0e4977803546a09807f681df21377c0a4c/LiveBedfiles/Pan4011_log.md#L37)):*
> ```Markdown
> The varscan and lofreq variant callers require flattened bedfiles, as any variants called within overlapping regions are called once for each region.
> This bedfile was created using the command:
> `cut -f1-3 /home/aled/Documents/mokabed/LiveBedfiles/Pan4011data.bed | bedtools merge -i - > /home/aled/Documents/mokabed/LiveBedfiles/Pan4011data_flat.bed`
> ```

Hi Aled - The `bedtools merge -i -` you have a hanging -, I assume its a typo which hasn't affected the results, or it is a flag which is missing?

**Review by Graeme-Smith — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/159)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @aledj2)

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/159)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith)

___
*[LiveBedfiles/Pan4011_log.md, line 37 at r1](https://reviewable.io/reviews/moka-guys/mokabed/159#-MLsBtTc0yjIVbMlZbDq:-MLsFx1A-fI1o3RaGIjI:b-rzwwpi) ([raw file](https://github.com/moka-guys/mokabed/blob/8b33ce0e4977803546a09807f681df21377c0a4c/LiveBedfiles/Pan4011_log.md#L37)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Hi Aled - The `bedtools merge -i -` you have a hanging -, I assume its a typo which hasn't affected the results, or it is a flag which is missing?
</blockquote></details>

the dash means stdin, ie the info piped in from the cut command

**Review by Graeme-Smith — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/159)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
