### PR TITLE
Pan5208

### PR DESCRIPTION
**Pull request by natashapinto**
New VCP1 Exomedepth readcount bed file

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/352)

### CODE REVIEW

**Review by rebeccahaines1 — CHANGES_REQUESTED** [review]
issue at capture.bed line 304 noted at commit r24. Checked later and this is resolved.

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 8 of 8 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, 2 of 2 files at r12, 2 of 2 files at r13, 2 of 2 files at r14, 1 of 1 files at r15, 7 of 7 files at r16, 1 of 1 files at r17, 2 of 2 files at r18, 2 of 2 files at r19, 2 of 2 files at r20, 2 of 2 files at r21, 2 of 2 files at r22, 2 of 2 files at r23, 2 of 2 files at r24, 2 of 2 files at r25, 2 of 2 files at r26, 2 of 2 files at r27, 11 of 11 files at r28, 2 of 2 files at r29, 2 of 2 files at r30, 11 of 11 files at r31, 2 of 2 files at r32, 2 of 2 files at r33, 20 of 20 files at r34, 1 of 1 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/352#-:-Nr_Vpr3D3JWMJgId5W4:bw3g3bx)* status: all files reviewed, 3 unresolved discussions (waiting on @natashapinto)

___
*[`LiveBedfiles/Pan5208_Logfile.md` line 2 at r35](https://reviewable.io/reviews/moka-guys/mokabed/352#-Nr_ZLWJ2yCJQ0gc7eIf:-Nr_ZLWJ2yCJQ0gc7eIg:b-wtcuc0) ([raw file](https://github.com/moka-guys/mokabed/blob/b24a9a8502f53c6b0bc11576b92de69e4aee3ca0/LiveBedfiles/Pan5208_Logfile.md#L2)):*
> ```Markdown
> ## Pan5208
> This VCP1 Exomedepth readcount BED file it is a remake of Pan5191. LDLR and PCSK9 were accidentally excluded from the bed file. Pan5206 will have up and down coding regions included and the 5UTR - no regions have been padded.
> ```

pan5208 not pan5206
___
*[`LiveBedfiles/Pan5208_Logfile.md` line 7 at r35](https://reviewable.io/reviews/moka-guys/mokabed/352#-Nr_ZOVH1cJZkWmlyd_h:-Nr_ZOVH1cJZkWmlyd_i:bhs85f5) ([raw file](https://github.com/moka-guys/mokabed/blob/b24a9a8502f53c6b0bc11576b92de69e4aee3ca0/LiveBedfiles/Pan5208_Logfile.md#L7)):*
> ```Markdown
>     Pan4291.bed- intronic variants relevant to Haematological genes 
>     Pan4290.bed- intronic variants for VCP1 regions 
>     Pan4292.bed- FH intronic variants padded by 5bp Pan4272.bed- intronic variants for CF 
> ```

please add new line before Pan4272
___
*[`LiveBedfiles/Pan5208_Logfile.md` line 140 at r35](https://reviewable.io/reviews/moka-guys/mokabed/352#-Nr_ZTA50p_qzSX_8t7P:-Nr_ZTA50p_qzSX_8t7Q:b-f74fxp) ([raw file](https://github.com/moka-guys/mokabed/blob/b24a9a8502f53c6b0bc11576b92de69e4aee3ca0/LiveBedfiles/Pan5208_Logfile.md#L140)):*
> ```Markdown
> 
> # Testing
> Pan5208_exomedepth.bed was tested using DNANexus app ED_readcount_analysis_v1.3.0 and the output RDATA file was tested using ED_cnv_calling_v1.3.0 to confirm compatibility in project 003_240223_exomedepth_bedfiles. The apps completed sucessfully.
> ```

please can the final bedfile be tested with the compare_genelists.py script too? To make sure nothing has been lost along the way

**Review by natashapinto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/352)* status: all files reviewed, 3 unresolved discussions (waiting on @rebeccahaines1)

___
*[`LiveBedfiles/Pan5208_Logfile.md` line 2 at r35](https://reviewable.io/reviews/moka-guys/mokabed/352#-Nr_ZLWJ2yCJQ0gc7eIf:-NraEjLaDd9-a1w7qnYm:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/b24a9a8502f53c6b0bc11576b92de69e4aee3ca0/LiveBedfiles/Pan5208_Logfile.md#L2)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

pan5208 not pan5206
</blockquote></details>

Done.
___
*[`LiveBedfiles/Pan5208_Logfile.md` line 7 at r35](https://reviewable.io/reviews/moka-guys/mokabed/352#-Nr_ZOVH1cJZkWmlyd_h:-NraEkxK2gP9p-Umd_OK:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/b24a9a8502f53c6b0bc11576b92de69e4aee3ca0/LiveBedfiles/Pan5208_Logfile.md#L7)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

please add new line before Pan4272
</blockquote></details>

Done.
___
*[`LiveBedfiles/Pan5208_Logfile.md` line 140 at r35](https://reviewable.io/reviews/moka-guys/mokabed/352#-Nr_ZTA50p_qzSX_8t7P:-NraElsb32u75qUdkkPq:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/b24a9a8502f53c6b0bc11576b92de69e4aee3ca0/LiveBedfiles/Pan5208_Logfile.md#L140)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

please can the final bedfile be tested with the compare_genelists.py script too? To make sure nothing has been lost along the way
</blockquote></details>

Done.

**Review by rebeccahaines1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r36, 2 of 2 files at r37, 2 of 2 files at r38, 1 of 1 files at r39, 2 of 2 files at r40, 2 of 2 files at r41, 2 of 2 files at r42, 1 of 1 files at r43, 4 of 4 files at r44, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/352)* status: all files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[`LiveBedfiles/Pan5208_Logfile.md` line 2 at r35](https://reviewable.io/reviews/moka-guys/mokabed/352#-Nr_ZLWJ2yCJQ0gc7eIf:-NraG31r1vHAjXQf-W6y:bkp66se) ([raw file](https://github.com/moka-guys/mokabed/blob/b24a9a8502f53c6b0bc11576b92de69e4aee3ca0/LiveBedfiles/Pan5208_Logfile.md#L2)):*
<details><summary><i>Previously, natashapinto (Natasha Pinto) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

third sentence still starts with Pan5206
___
*[`LiveBedfiles/Pan5208_Logfile.md` line 7 at r35](https://reviewable.io/reviews/moka-guys/mokabed/352#-Nr_ZOVH1cJZkWmlyd_h:-NraH60VBV1URqrF_Cq-:bwqr2dy) ([raw file](https://github.com/moka-guys/mokabed/blob/b24a9a8502f53c6b0bc11576b92de69e4aee3ca0/LiveBedfiles/Pan5208_Logfile.md#L7)):*
<details><summary><i>Previously, natashapinto (Natasha Pinto) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no new line still

**Review by natashapinto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/352)* status: 35 of 36 files reviewed, 1 unresolved discussion (waiting on @rebeccahaines1)

___
*[`LiveBedfiles/Pan5208_Logfile.md` line 2 at r35](https://reviewable.io/reviews/moka-guys/mokabed/352#-Nr_ZLWJ2yCJQ0gc7eIf:-NraJcEi53xekIY1Rz1X:bu27t7g) ([raw file](https://github.com/moka-guys/mokabed/blob/b24a9a8502f53c6b0bc11576b92de69e4aee3ca0/LiveBedfiles/Pan5208_Logfile.md#L2)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

third sentence still starts with Pan5206
</blockquote></details>

done-sorry forgot to commit the changes
___
*[`LiveBedfiles/Pan5208_Logfile.md` line 7 at r35](https://reviewable.io/reviews/moka-guys/mokabed/352#-Nr_ZOVH1cJZkWmlyd_h:-NraJh1PCIp07e4fBRww:bu27t7g) ([raw file](https://github.com/moka-guys/mokabed/blob/b24a9a8502f53c6b0bc11576b92de69e4aee3ca0/LiveBedfiles/Pan5208_Logfile.md#L7)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

no new line still
</blockquote></details>

done-sorry forgot to commit the changes

**Review by rebeccahaines1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/352#-:-NraOWabASghKjn-ilcC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @natashapinto)

**Pull request merged**
