### PR TITLE
Pan4553

### PR DESCRIPTION
**Pull request by natashapinto**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/230)

### CODE REVIEW

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/230)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @natashapinto)

___
*[LiveBedfiles/RequestForms/Pan4553.csv, line 16 at r11](https://reviewable.io/reviews/moka-guys/mokabed/230#-MdumRXI1KQbE46O_4q3:-MdumRXJEDBfjsew3rIq:b21jf7t) ([raw file](https://github.com/moka-guys/mokabed/blob/73bbf61714bd35e92fcae566a7ebec26537b0707/LiveBedfiles/RequestForms/Pan4553.csv#L16)):*
> ```
> No,
> ```
Yes
___
*[LiveBedfiles/RequestForms/Pan4553.csv, line 20 at r11](https://reviewable.io/reviews/moka-guys/mokabed/230#-MdumUIi7vnsF3aiurnE:-MdumUIi7vnsF3aiurnF:b7lsh62) ([raw file](https://github.com/moka-guys/mokabed/blob/73bbf61714bd35e92fcae566a7ebec26537b0707/LiveBedfiles/RequestForms/Pan4553.csv#L20)):*
> ```
> N/A
> ```
No

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/230)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @natashapinto)

___
*[LiveBedfiles/Pan4553dataRefSeqFormat.txt, line 1 at r12](https://reviewable.io/reviews/moka-guys/mokabed/230#-MdvnaZG7Ohh3yzzkKWG:-MdvnaZG7Ohh3yzzkKWH:bhv631k) ([raw file](https://github.com/moka-guys/mokabed/blob/eb74d91019218af35ce4d1a16f3922fadc60004d/LiveBedfiles/Pan4553dataRefSeqFormat.txt#L1)):*
> ```help
> #bin	name	chrom	strand	txStart	txEnd	cdsStart	cdsEnd	exonCount	exonStarts	exonSEnds	score	name2	cdsStartStat	cdsEndStat	exonFrames
> ```

this is incomplete so shouldn't be kept

**Review by natashapinto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/230)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @aledj2 and @natashapinto)

___
*[LiveBedfiles/RequestForms/Pan4553.csv, line 20 at r11](https://reviewable.io/reviews/moka-guys/mokabed/230#-MdumUIi7vnsF3aiurnE:-MdwKkETANL2Zas_Vtoe:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/73bbf61714bd35e92fcae566a7ebec26537b0707/LiveBedfiles/RequestForms/Pan4553.csv#L20)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> N/A
> ```
No
</blockquote></details>

Done.
___
*[LiveBedfiles/Pan4553dataRefSeqFormat.txt, line 1 at r12](https://reviewable.io/reviews/moka-guys/mokabed/230#-MdvnaZG7Ohh3yzzkKWG:-MdwKjE_E4fXH60FT9yX:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/eb74d91019218af35ce4d1a16f3922fadc60004d/LiveBedfiles/Pan4553dataRefSeqFormat.txt#L1)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

this is incomplete so shouldn't be kept
</blockquote></details>

Done.

**Review by aledj2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 1 of 8 files at r3, 1 of 3 files at r8, 1 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/230)* status: 5 of 12 files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[LiveBedfiles/RequestForms/Pan4553.csv, line 20 at r11](https://reviewable.io/reviews/moka-guys/mokabed/230#-MdumUIi7vnsF3aiurnE:-MdwLBrSBgUWJCZcU92G:b-5s4b3q) ([raw file](https://github.com/moka-guys/mokabed/blob/73bbf61714bd35e92fcae566a7ebec26537b0707/LiveBedfiles/RequestForms/Pan4553.csv#L20)):*
<details><summary><i>Previously, natashapinto wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry. not  done. (don't need to update logfile)

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/230)* status: 5 of 12 files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[LiveBedfiles/RequestForms/Pan4553.csv, line 20 at r11](https://reviewable.io/reviews/moka-guys/mokabed/230#-MdumUIi7vnsF3aiurnE:-MeP_ohS9pCMWIpBqtS8:bb7dx2z) ([raw file](https://github.com/moka-guys/mokabed/blob/73bbf61714bd35e92fcae566a7ebec26537b0707/LiveBedfiles/RequestForms/Pan4553.csv#L20)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

sorry. not  done. (don't need to update logfile)
</blockquote></details>

bump

**Review by aledj2 — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/230#-:-MeQGw6N5DMYfqcAq6h8:bg7igkv)* status: 6 of 12 files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
