### PR TITLE
Pan4990

### PR DESCRIPTION
**Pull request by rebeccahaines1**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/294)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
+@aledj2  

> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/294#-:-N5eRyFb9TmEmXs3VJCo:ba0a6h8)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @aledj2)

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/294)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @aledj2 and @rebeccahaines1)

___
*[`LiveBedfiles/Transcripts/Pan4990.txt` line 2 at r10](https://reviewable.io/reviews/moka-guys/mokabed/294#-N5eSpQjAS68m3DB4Ch3:-N5eSpQjAS68m3DB4Ch4:b-nv1bd6) ([raw file](https://github.com/moka-guys/mokabed/blob/9357b6b676e295bc47355a7e1ce205d2595cdab8/LiveBedfiles/Transcripts/Pan4990.txt#L2)):*
> ```help
> GuysAccession	ApprovedSymbol	GuysAccessionVersion
> NM_000504	F10	0
> ```

can this go into /pantranscripts folder please

**Review by rebeccahaines1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/294)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @aledj2)

___
*[`LiveBedfiles/Transcripts/Pan4990.txt` line 2 at r10](https://reviewable.io/reviews/moka-guys/mokabed/294#-N5eSpQjAS68m3DB4Ch3:-N5eUM8K2svS7bYUUHnf:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/9357b6b676e295bc47355a7e1ce205d2595cdab8/LiveBedfiles/Transcripts/Pan4990.txt#L2)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can this go into /pantranscripts folder please
</blockquote></details>

Done.

**Review by aledj2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 3 files at r4, 1 of 2 files at r9, 1 of 1 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/294#-:-N5eVaJj7K_j3Z3LN0Qx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2)

**Pull request merged**
