### PR TITLE
Pan5192

### PR DESCRIPTION
**Pull request by natashapinto**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/346)

### CODE REVIEW

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/346)* status: 0 of 55 files reviewed, 3 unresolved discussions (waiting on @natashapinto)

___
*[`LiveBedfiles/Pan5192_LogFile.md` line 75 at r12](https://reviewable.io/reviews/moka-guys/mokabed/346#-Nh1RLqM3_GDumTL1YDF:-Nh1RLqM3_GDumTL1YDG:b1l0je) ([raw file](https://github.com/moka-guys/mokabed/blob/cb0279ac892b05380e299d4b9f87f65fad29114c/LiveBedfiles/Pan5192_LogFile.md#L75)):*
> ```Markdown
> 
> NBEA;NM_015678.5 
> old - 13 35739230-35739235 new - 13 35739190-35743152
> ```

as discussed. the lama2 exon is padded upstream by 10bp
the NBEA coordinates are wrong



_Code quote:_
```Markdown
LAMA2;NM_000426.4
old - 6 129763366-129763372 new - 6	129764197-129764213

DIAPH1;NM_005219.5

old - 5	140915620-140915629 new - 5	140950984-140951013


NBEA;NM_015678.5
old - 13 35739230-35739235 new - 13 35739190-35743152
```
___
*[`LiveBedfiles/Pan5192data.bed` line 4724 at r12](https://reviewable.io/reviews/moka-guys/mokabed/346#-Nh1RZBx1X7g-zvXcD0B:-Nh1RZBx1X7g-zvXcD0C:bx5cjsw) ([raw file](https://github.com/moka-guys/mokabed/blob/cb0279ac892b05380e299d4b9f87f65fad29114c/LiveBedfiles/Pan5192data.bed#L4724)):*
> ```
> 6	129759790	129759907	3908										LAMA2;NM_000426.4
> 6	129761960	129762143	3908										LAMA2;NM_000426.4
> 6	129764197	129764213	3908										LAMA2;NM_000426.4
> ```

incorrect



_Code quote:_
```
129764197	129764213
```
___
*[`LiveBedfiles/Pan5192data.bed` line 8194 at r12](https://reviewable.io/reviews/moka-guys/mokabed/346#-Nh1RVQK1GQMCxGrz05W:-Nh1RVQLASd51BQlyaep:bx5cjsw) ([raw file](https://github.com/moka-guys/mokabed/blob/cb0279ac892b05380e299d4b9f87f65fad29114c/LiveBedfiles/Pan5192data.bed#L8194)):*
> ```
> 13	35735886	35736104	26960										NBEA;NM_001385012.1
> 13	35738492	35738647	26960										NBEA;NM_001385012.1
> 13	35739190	35743152	26960										NBEA;NM_001385012.1
> ```

incorrect



_Code quote:_
```
13	35739190	35743152
```

**Review by aledj2 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 15 of 15 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, 2 of 2 files at r12, 2 of 2 files at r13, 2 of 2 files at r14, 2 of 2 files at r15, 2 of 2 files at r16, 2 of 2 files at r17, 12 of 12 files at r18, 1 of 1 files at r19, 2 of 2 files at r20, 2 of 3 files at r21, 2 of 2 files at r22, 2 of 2 files at r23, 2 of 2 files at r24, 2 of 2 files at r25, 11 of 11 files at r26, 2 of 2 files at r27, 2 of 2 files at r28, 6 of 6 files at r29, 2 of 2 files at r30, 2 of 2 files at r31, 2 of 2 files at r32, 2 of 2 files at r33, 11 of 11 files at r34, 2 of 2 files at r35, 11 of 11 files at r36, 11 of 11 files at r37, 2 of 2 files at r38, 2 of 2 files at r39, 2 of 2 files at r40, 2 of 2 files at r41, 11 of 11 files at r42, 2 of 2 files at r43, 32 of 32 files at r44, 1 of 1 files at r45, 3 of 3 files at r46, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/346)* status: 53 of 55 files reviewed, 3 unresolved discussions (waiting on @natashapinto)

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/346)* status: 51 of 55 files reviewed, 4 unresolved discussions (waiting on @natashapinto)

___
*[`LiveBedfiles/Pan5192_exomedepth.bed` line 10812 at r48](https://reviewable.io/reviews/moka-guys/mokabed/346#-Nh3VkHE44l4dvsVig4I:-Nh3VkHF1Q1EM3gY4ZYW:b-335igx) ([raw file](https://github.com/moka-guys/mokabed/blob/bd3fcad470c1b0d269cc50db7c845872999642b7/LiveBedfiles/Pan5192_exomedepth.bed#L10812)):*
> ```
> 6	129759790	129759907	LAMA2_42
> 6	129761960	129762143	LAMA2_43
> 6	129764213	129764213	LAMA2_44
> ```

this is same as stop - needs correcting



_Code quote:_
```
129764213
```

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/346)* status: 51 of 55 files reviewed, 5 unresolved discussions (waiting on @natashapinto)

___
*[`LiveBedfiles/RequestForms/Pan5192.csv` line 11 at r50](https://reviewable.io/reviews/moka-guys/mokabed/346#-Nh3XKf073nlFv7OD3Ly:-Nh3XKf19EC9kXTcqf-y:b-6mzum8) ([raw file](https://github.com/moka-guys/mokabed/blob/84471083499f661907b8c6cccc9de7d75da32708/LiveBedfiles/RequestForms/Pan5192.csv#L11)):*
> ```CSV
> 2, Panel description/name (fill in a-c from Moka),
> 2, a) Category,VCP3
> 2, b) SubCategory,No padding +5UTR+Pan4535 with additional genes
> ```

pan3608&5167



_Code quote:_
```CSV
Pan4535
```

**Review by rebeccahaines1 — APPROVED** [review]
> Reviewed 4 of 4 files at r51, 1 of 1 files at r52, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/346)* status: all files reviewed, 5 unresolved discussions (waiting on @natashapinto)

**Review by rebeccahaines1 — APPROVED** [review]
> Dismissed @aledj2 from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/346)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @natashapinto)

**Pull request merged**
