### PR TITLE
Pan4909

### PR DESCRIPTION
**Pull request by natashapinto**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/271)

### CODE REVIEW

**Review by natashapinto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/271)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @aledj2)

___
*[LiveBedfiles/Pan4292_LogFile.txt, line 8 at r8](https://reviewable.io/reviews/moka-guys/mokabed/271#-MuM9XbO33Vs_MuCkuNm:-MuPxMhK5QoUVxzwtvEq:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/c267ca7599fdb00f9ee284f13ce2b31833ce2d2b/LiveBedfiles/Pan4292_LogFile.txt#L8)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Add testing statement
</blockquote></details>

Done.
___
*[LiveBedfiles/Pan4909.bed, line 2 at r8](https://reviewable.io/reviews/moka-guys/mokabed/271#-MuM9SfREmTxJpgorOTl:-MuPxOF54FPPE4VrgkrW:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/c267ca7599fdb00f9ee284f13ce2b31833ce2d2b/LiveBedfiles/Pan4909.bed#L2)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

does it need to be resorted?
</blockquote></details>

Done.

**Review by rebeccahaines1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 3 of 3 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, 3 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/271)* status: all files reviewed, 2 unresolved discussions (waiting on @aledj2)

**Review by rebeccahaines1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/271)* status: all files reviewed, 2 unresolved discussions (waiting on @aledj2)

**Review by rebeccahaines1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/271)* status: all files reviewed, 2 unresolved discussions (waiting on @aledj2)

**Review by rebeccahaines1 — APPROVED** [review]
> Dismissed @aledj2 from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @natashapinto)

**Pull request merged**
