### PR TITLE
Gene comparison script

### PR DESCRIPTION
**Pull request by natashapinto**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/351)

### CODE REVIEW

**Review by rebeccahaines1 — CHANGES_REQUESTED** [review]
Please can you add a few lines to the repo readme about this script. Or maybe slightly more info in the comment at the beginning to indicate how the script is used. Most detail should be in the SOP, but I think this would benefit from some clarification in the script

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/351#-:-NrAPDt063_IDLxq91rm:b-6oc70r)* status: all files reviewed, 2 unresolved discussions (waiting on @natashapinto)

___
*[`LiveBedfiles/TestArea_for_bed_generation_script/compare_genelists.py` line 5 at r1](https://reviewable.io/reviews/moka-guys/mokabed/351#-NrAOftK47qvuVj1R780:-NrAOftK47qvuVj1R781:b-4aaqmd) ([raw file](https://github.com/moka-guys/mokabed/blob/8a26ac52ee44f65d9f123f7856a062531941986b/LiveBedfiles/TestArea_for_bed_generation_script/compare_genelists.py#L5)):*
> ```Python
> 
> ## Script compares genes listed in a BED file and genes listed in a BED file request form to identify missing genes.
> ## Input files have to be in csv format
> ```

Assume bed file is still acceptable input?
___
*[`LiveBedfiles/TestArea_for_bed_generation_script/compare_genelists.py` line 17 at r1](https://reviewable.io/reviews/moka-guys/mokabed/351#-NrAP-n81PRs00K-dN62:-NrAP-n81PRs00K-dN63:brbsqju) ([raw file](https://github.com/moka-guys/mokabed/blob/8a26ac52ee44f65d9f123f7856a062531941986b/LiveBedfiles/TestArea_for_bed_generation_script/compare_genelists.py#L17)):*
> ```Python
> 
>     # Find data missing in file 1
>     missing_in_file1 = column_data2 - column_data1
> ```

can we also do the opposite of this- i.e. column_data1 - column_data2 ?

**Review by natashapinto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/351)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @rebeccahaines1)

___
*[`LiveBedfiles/TestArea_for_bed_generation_script/compare_genelists.py` line 5 at r1](https://reviewable.io/reviews/moka-guys/mokabed/351#-NrAOftK47qvuVj1R780:-NrATxRe1nM5YB2225t8:bhnrgz0) ([raw file](https://github.com/moka-guys/mokabed/blob/8a26ac52ee44f65d9f123f7856a062531941986b/LiveBedfiles/TestArea_for_bed_generation_script/compare_genelists.py#L5)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

Assume bed file is still acceptable input?
</blockquote></details>

Format is now specified in the README
___
*[`LiveBedfiles/TestArea_for_bed_generation_script/compare_genelists.py` line 17 at r1](https://reviewable.io/reviews/moka-guys/mokabed/351#-NrAP-n81PRs00K-dN62:-NrAU-_81VOfTbtI6dRa:b-b19gbp) ([raw file](https://github.com/moka-guys/mokabed/blob/8a26ac52ee44f65d9f123f7856a062531941986b/LiveBedfiles/TestArea_for_bed_generation_script/compare_genelists.py#L17)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

can we also do the opposite of this- i.e. column_data1 - column_data2 ?
</blockquote></details>

You can swap the files in command line to do this, specified in the README

**Review by rebeccahaines1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/351)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @natashapinto)

**Review by rebeccahaines1 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/351)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @natashapinto)

**Pull request merged**
