### PR TITLE
Pan4082

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/162)

### CODE REVIEW

**Review by Graeme-Smith — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/162)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2)

**Review by Graeme-Smith — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

___
*[LiveBedfiles/Pan4082.log, line 3 at r1](https://reviewable.io/reviews/moka-guys/mokabed/162#-MNidnb989AwWN7uulWD:-MNilIVN6MDRGA4t9uVw:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/88e912101ff505ead330004dc922038b6cf5572f/LiveBedfiles/Pan4082.log#L3)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Could you change 'but where the bed file used to clip' to something clearer such as 'but where the previous bed file clipped primers and flattened the BED file used for variant calling the new version is adjusted to enable variants at the primer-amplicon border to be detected.'
</blockquote></details>

Done.

**Review by Graeme-Smith — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
