### PR TITLE
Pan4565

### PR DESCRIPTION
**Pull request by natashapinto**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/235)

### CODE REVIEW

**Review by aledj2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 8 files at r3, 1 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/235)* status: 5 of 14 files reviewed, 4 unresolved discussions (waiting on @natashapinto)

___
*[LiveBedfiles/Pan4554_sorted.bed, line 0 at r10](https://reviewable.io/reviews/moka-guys/mokabed/235#-MdvIU6vEH8LVj_M7SmW:-MdvIU6wCz4Y3M2oieWB:buriy9i) ([raw file](https://github.com/moka-guys/mokabed/blob/3db4750bfe5b61b66593dc0a6794baa8c7d36a56/LiveBedfiles/Pan4554_sorted.bed#L0)):*
please delete - wrong pan number
___
*[LiveBedfiles/RequestForms/Pan4565.csv, line 11 at r2](https://reviewable.io/reviews/moka-guys/mokabed/235#-MdvGPjO8pbvxW9x5Yai:-MdvGPjO8pbvxW9x5Yaj:b-ytx4fl) ([raw file](https://github.com/moka-guys/mokabed/blob/5965e8bea64b1689c42c4d5889f76d2cbc224eff/LiveBedfiles/RequestForms/Pan4565.csv#L11)):*
> ```CSV
> 2. b) SubCategory,R57_Childhood onset dystonia or chorea or related movement disorder,
> 2. c) Panel,VCP3 Viapath R57_Childhood onset dystonia or chorea or related movement disorder,
> 3. Is this BED file for RPKM?,No,
> ```

exome depth Q's
___
*[LiveBedfiles/RequestForms/Pan4565.csv, line 15 at r2](https://reviewable.io/reviews/moka-guys/mokabed/235#-MdvGS8tEkadSaTSufGf:-MdvGS8tEkadSaTSufGg:bb7sa0t) ([raw file](https://github.com/moka-guys/mokabed/blob/5965e8bea64b1689c42c4d5889f76d2cbc224eff/LiveBedfiles/RequestForms/Pan4565.csv#L15)):*
> ```CSV
> 4. b) If yes, does this need further padding?",N/A,
> 5. a) Should specific transcripts be used to create the bed file? (as opposed to all transcripts) Specific transcripts - see Moka,Yes - see below,
> 5. b) If specific transcripts are to be used have you provided multiple transcripts for the same gene? (if Yes please state),No,
> ```

yes?
___
*[LiveBedfiles/RequestForms/Pan4565.csv, line 17 at r2](https://reviewable.io/reviews/moka-guys/mokabed/235#-MdvGTUC-loFIB3jqPXU:-MdvGTUC-loFIB3jqPXV:b32w12) ([raw file](https://github.com/moka-guys/mokabed/blob/5965e8bea64b1689c42c4d5889f76d2cbc224eff/LiveBedfiles/RequestForms/Pan4565.csv#L17)):*
> ```CSV
> 5. b) If specific transcripts are to be used have you provided multiple transcripts for the same gene? (if Yes please state),No,
> 6. What padding is required around the exons?,30bp,
> 7. a) Should UTRs be included for ALL genes?,N/A,
> ```

No

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/235)* status: 4 of 14 files reviewed, 5 unresolved discussions (waiting on @natashapinto)

___
*[LiveBedfiles/Pan4565dataRefSeqFormat.txt, line 1 at r13](https://reviewable.io/reviews/moka-guys/mokabed/235#-MdvnxqK4dTFXpbwgYY-:-MdvnxqK4dTFXpbwgYY0:bnkbqxo) ([raw file](https://github.com/moka-guys/mokabed/blob/cfd7c4cbfdb9813319aacf089aa8d7a4db57ad2c/LiveBedfiles/Pan4565dataRefSeqFormat.txt#L1)):*
> ```help
> #bin	name	chrom	strand	txStart	txEnd	cdsStart	cdsEnd	exonCount	exonStarts	exonSEnds	score	name2	cdsStartStat	cdsEndStat	exonFrames
> ```

incomplete so shouldn't be kept

**Review by natashapinto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/235)* status: 4 of 14 files reviewed, 5 unresolved discussions (waiting on @aledj2)

___
*[LiveBedfiles/RequestForms/Pan4565.csv, line 11 at r2](https://reviewable.io/reviews/moka-guys/mokabed/235#-MdvGPjO8pbvxW9x5Yai:-MdwglED-eq_nEatKJHb:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/5965e8bea64b1689c42c4d5889f76d2cbc224eff/LiveBedfiles/RequestForms/Pan4565.csv#L11)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

exome depth Q's
</blockquote></details>

Done.
___
*[LiveBedfiles/RequestForms/Pan4565.csv, line 15 at r2](https://reviewable.io/reviews/moka-guys/mokabed/235#-MdvGS8tEkadSaTSufGf:-MdwglXC1wISQS-5KtAx:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/5965e8bea64b1689c42c4d5889f76d2cbc224eff/LiveBedfiles/RequestForms/Pan4565.csv#L15)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

yes?
</blockquote></details>

Done.
___
*[LiveBedfiles/RequestForms/Pan4565.csv, line 17 at r2](https://reviewable.io/reviews/moka-guys/mokabed/235#-MdvGTUC-loFIB3jqPXU:-MdwgllI4K6_K1rihUdt:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/5965e8bea64b1689c42c4d5889f76d2cbc224eff/LiveBedfiles/RequestForms/Pan4565.csv#L17)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

No
</blockquote></details>

Done.
___
*[LiveBedfiles/Pan4554_sorted.bed, line  at r10](https://reviewable.io/reviews/moka-guys/mokabed/235#-MdvIU6vEH8LVj_M7SmW:-MdwgE9zAfsLBU1-XtpG:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/3db4750bfe5b61b66593dc0a6794baa8c7d36a56/LiveBedfiles/Pan4554_sorted.bed#L)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

please delete - wrong pan number
</blockquote></details>

Done.
___
*[LiveBedfiles/Pan4565dataRefSeqFormat.txt, line 1 at r13](https://reviewable.io/reviews/moka-guys/mokabed/235#-MdvnxqK4dTFXpbwgYY-:-Mdwgv4F3MuwBD4nl5_b:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/cfd7c4cbfdb9813319aacf089aa8d7a4db57ad2c/LiveBedfiles/Pan4565dataRefSeqFormat.txt#L1)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

incomplete so shouldn't be kept
</blockquote></details>

Done.

**Review by aledj2 — APPROVED** [review]
> Reviewed 2 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/235)* status: 6 of 14 files reviewed, all discussions resolved (waiting on @natashapinto)

**Review by aledj2 — APPROVED** [review]
> Reviewed 2 of 3 files at r12, 1 of 2 files at r15, 1 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/235)* status: 10 of 14 files reviewed, all discussions resolved (waiting on @natashapinto)

**Pull request merged**
