### PR TITLE
add Pan5230 files

### PR DESCRIPTION
**Pull request by natashapinto**
- Created new folder for Bedmaker
- Added all files used to create Pan5230 bedfiles
- Saved outputs from Bedmaker

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/360)

### CODE REVIEW

**Review by rebeccahaines1 — CHANGES_REQUESTED** [review]
looks good, but please can you add the log file we discussed? Thanks

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/360#-:-ODwxK0zBRj9ejOrtPox:bs02dxn)* status: all files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[`Bedmaker/Pan5230/Pan5230_exomeDepth.bed` line 0 at r1](https://reviewable.io/reviews/moka-guys/mokabed/360#-ODwwqwPEWRDNHArAO9e:-ODwwqwPEWRDNHArAO9f:bwyj7rd) ([raw file](https://github.com/moka-guys/mokabed/blob/8fab3e07d735fb55e783731812ce00d7a29bcaa0/Bedmaker/Pan5230/Pan5230_exomeDepth.bed#L0)):*
I've changed my mind- this file has fewer lines than the data.bed and sambamba.bed files, and I'm not sure why. It's also got all of the SNPs in it, which we don't want to do copy number calling on. Please can you remove it, and we can make the ED bedfile in the future

**Review by natashapinto — COMMENTED** [review]
oops forgot to add it, its there now

> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/360#-:-OE-GpoSDGllKWU2NW_p:b-ojjmqk)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @rebeccahaines1)

___
*[`Bedmaker/Pan5230/Pan5230_exomeDepth.bed` line  at r1](https://reviewable.io/reviews/moka-guys/mokabed/360#-ODwwqwPEWRDNHArAO9e:-OE-Gu4r9D8WVWMKxSma:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/8fab3e07d735fb55e783731812ce00d7a29bcaa0/Bedmaker/Pan5230/Pan5230_exomeDepth.bed#L)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

I've changed my mind- this file has fewer lines than the data.bed and sambamba.bed files, and I'm not sure why. It's also got all of the SNPs in it, which we don't want to do copy number calling on. Please can you remove it, and we can make the ED bedfile in the future
</blockquote></details>

Done.

**Review by rebeccahaines1 — CHANGES_REQUESTED** [review]
thanks. did you do any sense checking of the previously identified problematic regions from vcp3?

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/360#-:-OE-JKQD5RbLVGMcm2ce:b-dqbd32)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @natashapinto)

___
*[`Bedmaker/Pan5230/CP2bed_logfile.md` line 5 at r2](https://reviewable.io/reviews/moka-guys/mokabed/360#-OE-IleYC5LxuokXgo3N:-OE-IleYC5LxuokXgo3O:baywhnd) ([raw file](https://github.com/moka-guys/mokabed/blob/45be8f39ab3df1f6678cc95943d6d36d50a73243/Bedmaker/Pan5230/CP2bed_logfile.md#L5)):*
> ```Markdown
> 
> To include:
> - Genes that are included in R code tests that will be tested on CP2, provided as a transcript ID with a version (see text file XXX)
> ```

can you update the filename please. also for the next line. 
___
*[`Bedmaker/Pan5230/CP2bed_logfile.md` line 8 at r2](https://reviewable.io/reviews/moka-guys/mokabed/360#-OE-Ir3pBo_XeYgq6kgs:-OE-Ir3pBo_XeYgq6kgt:bba9b3c) ([raw file](https://github.com/moka-guys/mokabed/blob/45be8f39ab3df1f6678cc95943d6d36d50a73243/Bedmaker/Pan5230/CP2bed_logfile.md#L8)):*
> ```Markdown
> - Genes that are not included on R code tests at the moment, provided as gene name. BEDmaker will select the MANE transcript equivalent or the Ensembl canonical transcript if the MANE equivalent is unavailable. (File XXX)
> - SNPs (for FH PRS and know pathogenic SNPs in other regions) Provided as a list of rsIDs (CP2_pathogenicsnps_wrsids.txt)
> - Genomic regions (some SNPs, some known clinically important non-coding regions) provided as a list of regions (CP2_pathogenic_snps_norsids.txt padded by +/-5bp)
> ```

add ref to the FXR1 additional region
maybe specify that this region is for the muscle specific transcript described in https://doi.org/10.1038/s41467-019-08548-9
___
*[`Bedmaker/Pan5230/CP2bed_logfile.md` line 20 at r2](https://reviewable.io/reviews/moka-guys/mokabed/360#-OE-JCZp0eS1ae-nhB3b:-OE-JCZp0eS1ae-nhB3c:bw2tq07) ([raw file](https://github.com/moka-guys/mokabed/blob/45be8f39ab3df1f6678cc95943d6d36d50a73243/Bedmaker/Pan5230/CP2bed_logfile.md#L20)):*
> ```Markdown
> Lists produced by R Haines and N Pinto using information from Heidi and Michael. 
> 
> Lists reviewed by XXX prior to Bed file being used
> ```

maybe remove this line as it hasn't been done

**Review by natashapinto — COMMENTED** [review]
Yes, LAMA2 and DIAPH1 look fine but NBEA gene isn't included in CP2

> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/360#-:-OE-X3C60yBvgtmTSLPh:b-y0jt9)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @rebeccahaines1)

___
*[`Bedmaker/Pan5230/CP2bed_logfile.md` line 5 at r2](https://reviewable.io/reviews/moka-guys/mokabed/360#-OE-IleYC5LxuokXgo3N:-OE-RgUU7l60GP108lDL:b3dyfxl) ([raw file](https://github.com/moka-guys/mokabed/blob/45be8f39ab3df1f6678cc95943d6d36d50a73243/Bedmaker/Pan5230/CP2bed_logfile.md#L5)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

can you update the filename please. also for the next line.
</blockquote></details>

sorry somehow managed to save the wrong version. The correct logfile is saved now
___
*[`Bedmaker/Pan5230/CP2bed_logfile.md` line 8 at r2](https://reviewable.io/reviews/moka-guys/mokabed/360#-OE-Ir3pBo_XeYgq6kgs:-OE-S4p93CYQZrIc05mC:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/45be8f39ab3df1f6678cc95943d6d36d50a73243/Bedmaker/Pan5230/CP2bed_logfile.md#L8)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

add ref to the FXR1 additional region
maybe specify that this region is for the muscle specific transcript described in https://doi.org/10.1038/s41467-019-08548-9
</blockquote></details>

Done.
___
*[`Bedmaker/Pan5230/CP2bed_logfile.md` line 20 at r2](https://reviewable.io/reviews/moka-guys/mokabed/360#-OE-JCZp0eS1ae-nhB3b:-OE-S4U65I77EwORNtDF:b-896fix) ([raw file](https://github.com/moka-guys/mokabed/blob/45be8f39ab3df1f6678cc95943d6d36d50a73243/Bedmaker/Pan5230/CP2bed_logfile.md#L20)):*
<details><summary><i>Previously, rebeccahaines1 wrote…</i></summary><blockquote>

maybe remove this line as it hasn't been done
</blockquote></details>

Done.

**Review by rebeccahaines1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/mokabed/360)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @natashapinto)

**Pull request merged**
